export const cards = [
    {
        id: 1,
        url: "images/laptop1.jpg",
        ramSize: "4 GB",
        storageCapacity: "256 GB SSD",
        modelName: 'T440S - 14,1"',
        bateryLife: "24 hrs",
        processorType: "Intel® Core™ i5-4300U",
        processorSpeed: "2.9 GHz",
        graphicCard: "Intel HD Graphics",
        price: "500$",
        status: "sealed",
        mark: "LENOVO THINKPAD",
        click: "view",
    },
    {
        id: 2,
        url: "images/laptop2.jpg",
        ramSize: "4 GB",
        storageCapacity: "128 GB SSD",
        modelName: 'T440S - 14,1"',
        bateryLife: "50%",
        processorType: "Intel® Core™ i5-4300U",
        processorSpeed: "1.9 GHz",
        graphicCard: "Intel HD Graphics",
        price: "250$",
        status: "sealed",
        mark: "LENOVO THINKPAD",
        click: "view",
    },
    {
        id: 3,
        url: "images/14pro_max.jpg",
        ramSize: "8 GB",
        storageCapacity: "12 GB SSD",
        modelName: 'T440S - 14,1"',
        bateryLife: "100%",
        processorType: "Intel® Core™ i5-4300U",
        processorSpeed: "1.9 GHz",
        graphicCard: "Intel HD Graphics",
        price: "250$",
        status: "sealed",
        mark: "LENOVO THINKPAD",
        click: "view",
    },
    {
        id: 4,
        url: "images/ps4.jpg",
        ramSize: "8 GB",
        storageCapacity: "12 GB SSD",
        modelName: 'T440S - 14,1"',
        bateryLife: "100%",
        processorType: "Intel® Core™ i5-4300U",
        processorSpeed: "1.9 GHz",
        graphicCard: "Intel HD Graphics",
        price: "250$",
        status: "sealed",
        mark: "LENOVO THINKPAD",
        click: "view",
    },
    {
        id: 5,
        url: "images/s22.jpg",
        ramSize: "8 GB",
        storageCapacity: "12 GB SSD",
        modelName: 'T440S - 14,1"',
        bateryLife: "100%",
        processorType: "Intel® Core™ i5-4300U",
        processorSpeed: "1.9 GHz",
        graphicCard: "Intel HD Graphics",
        price: "250$",
        status: "sealed",
        mark: "LENOVO THINKPAD",
        click: "view",
    },
    {
        id: 6,
        url: "images/laptop2.jpg",
        ramSize: "8 GB",
        storageCapacity: "12 GB SSD",
        modelName: 'T440S - 14,1"',
        bateryLife: "100%",
        processorType: "Intel® Core™ i5-4300U",
        processorSpeed: "1.9 GHz",
        graphicCard: "Intel HD Graphics",
        price: "250$",
        status: "sealed",
        mark: "LENOVO THINKPAD",
        click: "view",
    },
    {
        id: 3,
        url: "images/14pro_max.jpg",
        ramSize: "8 GB",
        storageCapacity: "12 GB SSD",
        modelName: 'T440S - 14,1"',
        bateryLife: "100%",
        processorType: "Intel® Core™ i5-4300U",
        processorSpeed: "1.9 GHz",
        graphicCard: "Intel HD Graphics",
        price: "250$",
        status: "sealed",
        mark: "LENOVO THINKPAD",
        click: "view",
    },
    {
        id: 3,
        url: "images/14pro_max.jpg",
        ramSize: "8 GB",
        storageCapacity: "12 GB SSD",
        modelName: 'T440S - 14,1"',
        bateryLife: "100%",
        processorType: "Intel® Core™ i5-4300U",
        processorSpeed: "1.9 GHz",
        graphicCard: "Intel HD Graphics",
        price: "250$",
        status: "sealed",
        mark: "LENOVO THINKPAD",
        click: "view",
    },
    {
        id: 3,
        url: "images/14pro_max.jpg",
        ramSize: "8 GB",
        storageCapacity: "12 GB SSD",
        modelName: 'T440S - 14,1"',
        bateryLife: "100%",
        processorType: "Intel® Core™ i5-4300U",
        processorSpeed: "1.9 GHz",
        graphicCard: "Intel HD Graphics",
        price: "250$",
        status: "sealed",
        mark: "LENOVO THINKPAD",
        click: "view",
    },
];